### ISSUE TITLE
Noise doesnt change often enough, gives a smearing effect

### ISSUE THREAD

**Issue by labbo-lab** [MaxBittker/sandspiel-studio#130]
Noise doesnt change often enough, gives a smearing effect
(not sure if this is intentional or not)

<img width="414" alt="image" src="https://user-images.githubusercontent.com/62490883/191067619-0e550434-2b8a-4013-b6ce-dfcd64830716.png">

**Comment by TodePond** [comment]
Hey, yeah we're experimenting some different styles of noise at the moment - we're going to try some more things to improve it

**Comment by MaxBittker** [comment]
gonna close this for now because i like the effect
