### ISSUE TITLE
`that` block

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#23]
![image](https://user-images.githubusercontent.com/15892272/160093542-1fd0c143-e3a1-47e0-bdca-653904137905.png)
![image](https://user-images.githubusercontent.com/15892272/160094006-c303b4b9-be2c-4f2d-a7b5-a4b4e6c62170.png)
![image](https://user-images.githubusercontent.com/15892272/160094031-9861239b-bf7d-42b5-a5a7-cbb473546d8a.png)

**Comment by MaxBittker** [comment]
this could also be a "let" block (was really wanting this today!)

**Comment by TodePond** [comment]
Closing for now! maybe revisit in distant future
