### ISSUE TITLE
There should be options for setting the edge of the world (element and/or wraparound)

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#62]
By default, the edge of the world is made up of Wall. If you change Wall, eg: by renaming it to another element, this can cause some unexpected behaviours at the edge of the world.

**Comment by MaxBittker** [comment]
i wonder what the edge of the world should be made of...

**Comment by TodePond** [comment]
What if... the first two elements can't be renamed? What if they're always `Air` and `Wall` or something along those lines? To make it clear what they do. Or perhaps.. `Empty` and `Edge`... I don't know though. It would be a shame to not be able to change them.

Perhaps some simple options would be better - that let you pick what elements get chosen for the air and edge?
Like a dropdown below the simulation / next to the reset button.

Or perhaps rename the reset button to make it clearer? 
`Fill world with Air`
`Set world edge to Wall`

**Comment by TodePond** [comment]
Would also be good to be able to set the edge to 'wraparound'

**Comment by TodePond** [comment]
The world now wraps around. By default, the world has a Wall border, which can be cleared/removed
