### ISSUE TITLE
Add a `change next frame` block!?

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#66]
It would change the element AFTER every element has behaved, but BEFORE the elements start behaving next frame. Like... in between frames.

This would make it easy to make traditional cellular automata like game of life.

For example, here's how to make the Alive element:

![image](https://user-images.githubusercontent.com/15892272/169000717-314f79e2-17c4-4cca-8270-5ac75a0092f1.png)

**Comment by MaxBittker** [comment]
this feels weird :/ but i really want easy CA rules...

**Comment by TodePond** [comment]
Yes it does feel weird. I wonder if there's better way to word/phrase it.

Or maybe it could be another expandable dropdown thing.

Default:
`change me into Dead +`

After clicking plus:
`change me into Dead ( now ▼ ) -`
`change me into Dead ( next frame ▼ ) " -`

**Comment by TodePond** [comment]
Done
