### ISSUE TITLE
`change` block should maybe keep color data unchanged?

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#68]
When I was making some firework elements, it was really annoying that `change` reset the hue value to 0. I wanted to change a rocket into an explosion - and KEEP the hue value.

Maybe we could make it keep hue unchanged? Are there any potential pitfalls of this?

Another alternative could be: Allow the data blocks to change 'species' again, which could behave in this way.

**Comment by MaxBittker** [comment]
i like this solution: 

Another alternative could be: Allow the data blocks to change 'species' again, which could behave in this way.

**Comment by TodePond** [comment]
I agree!
