### ISSUE TITLE
Make our own plus/minus blocks

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#8]
Because I haven't got to them yet! 

I'm currently experimenting with the best way of implementing them. Watch this space!

**Comment by TodePond** [comment]
- [ ] Element Group
- [ ] If Else If (placeholder)
- [ ] If Else
- [ ] Number/Vector Operation
- [ ] Boolean Operation

**Comment by MaxBittker** [comment]
@TodePond safe to close this? :)
