### ISSUE TITLE
`Reset` vs `Clear` button

### ISSUE THREAD

**Issue by TodePond** [MaxBittker/sandspiel-studio#80]
I think the Reset button should set the world to what it was when the post loads.

There should be a separate Clear button that empties the screen maybe!

**Comment by TodePond** [comment]
Done!

**Comment by mdtrooper** [comment]
Where is the reset button in the public demo?

Because some examples need to reload entire web for reload it, for example: https://github.com/MaxBittker/sandspiel-studio.git
